apiVersion: v1
kind: Service
metadata:
  name: budget-sync-web
  labels:
    app: budget-sync-web
spec:
  type: ClusterIP
  selector:
    app: budget-sync-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
