mutation UpdateTransactionCategory($input: UpdateTransactionCategoryInput!) {
  updateTransactionCategory(input: $input) {
    id
    category {
      id
      name
    }
    categorizationStatus
  }
}

mutation UpdateTransactionBudget($input: UpdateTransactionBudgetInput!) {
  updateTransactionBudget(input: $input) {
    id
    budget {
      id
      name
    }
    categorizationStatus
  }
}

mutation UpdateTransactionNotes($input: UpdateTransactionNotesInput!) {
  updateTransactionNotes(input: $input) {
    id
    notes
  }
}

mutation VerifyTransaction($id: Int!) {
  verifyTransaction(id: $id) {
    id
    categorizationStatus
  }
}
